name: 'Nuget package version'
description: 'Detect nuget package versions'
branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  package:
    description: 'Uniq package name'
    required: true

outputs:
  all:
    description: 'JSON array of available package versions'
    value: ${{ steps.fetch-info.outputs.all }}
  latest:
    description: 'Latest package version'
    value: ${{ steps.fetch-info.outputs.latest }}

runs:
  using: 'composite'
  steps: 
    - name: Fetch info
      id: fetch-info
      shell: bash
      run: |
        export RAW_RESPONSE=$(curl https://api.nuget.org/v3-flatcontainer/${{ inputs.package }}/index.json)
        export JSON_ARRAY=$(echo $RAW_RESPONSE | jq ".versions")
        export LATEST_VERSION=$(echo $JSON_ARRAY | jq "last" | sed 's/\"//g')
        
        echo $JSON_ARRAY
        echo $LATEST_VERSION

        echo "all=$(echo $JSON_ARRAY)" >> $GITHUB_OUTPUT
        echo "latest=$(echo $LATEST_VERSION)" >> $GITHUB_OUTPUT
